name: interactive_desktop_widget
description: A decoration for your desktop.
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  rive: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

