name: cute_doggo
description: A decoration for your desktop.
publish_to: 'none' 
version: 0.1.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter:
    sdk: flutter
  rive: ^0.9.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_icons:
  image_path: "assets/icons/dog.png"
  linux:
    generate: true
  macos:
    generate: true
  web:
    generate: false
  windows:
    generate: true
