name: interactive_desktop_widget
description: A decoration for your desktop.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  # fluent_ui: ^4.1.0
  flutter:
    sdk: flutter
  # flutter_acrylic: ^1.0.0+2
  # native_context_menu: ^0.2.2+5
  rive: ^0.9.1
  # window_manager: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

